name = "BidHandler"
log_level = "debug"

[profiles]
address = "profile-manager:80"

[profile_state]
address = "state-service:80"

[server]
port = "80"

[semantic_targeting]
path = "./dict"
min_similarity = 0.5