[app]
name = "EventCollector"
port = ":80"
log_level = "debug"

[redis]
connection_string = "redis://redis:6379/0"

[reader]
num_of_readers = 10
buffer_size = 100

[druid]
ingest_url = "http://druid-router:8888/"
datasource = "events"

[writer]
num_of_writers = 10
flush_timeout = 10
max_size = 10