[app]
name = "EventCollector"
port = ":8081"
log_level = "debug"

[redis]
connection_string = "redis://localhost:6379/0"

[reader]
num_of_readers = 10
buffer_size = 100

[druid]
ingest_url = "http://localhost:8888/druid/indexer/v2/task"
datasource = "event"

[writer]
num_of_writers = 11
flush_timeout = "10s"
max_size = 10