// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: package.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPackagesWithZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageIds    []string               `protobuf:"bytes,1,rep,name=package_ids,json=packageIds,proto3" json:"package_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackagesWithZonesRequest) Reset() {
	*x = GetPackagesWithZonesRequest{}
	mi := &file_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackagesWithZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackagesWithZonesRequest) ProtoMessage() {}

func (x *GetPackagesWithZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackagesWithZonesRequest.ProtoReflect.Descriptor instead.
func (*GetPackagesWithZonesRequest) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{0}
}

func (x *GetPackagesWithZonesRequest) GetPackageIds() []string {
	if x != nil {
		return x.PackageIds
	}
	return nil
}

type GetPackagesWithZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*Package             `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackagesWithZonesResponse) Reset() {
	*x = GetPackagesWithZonesResponse{}
	mi := &file_package_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackagesWithZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackagesWithZonesResponse) ProtoMessage() {}

func (x *GetPackagesWithZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackagesWithZonesResponse.ProtoReflect.Descriptor instead.
func (*GetPackagesWithZonesResponse) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{1}
}

func (x *GetPackagesWithZonesResponse) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ZoneIds       []string               `protobuf:"bytes,3,rep,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_package_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{2}
}

func (x *Package) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetZoneIds() []string {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

var File_package_proto protoreflect.FileDescriptor

const file_package_proto_rawDesc = "" +
	"\n" +
	"\rpackage.proto\x12\x02pb\">\n" +
	"\x1bGetPackagesWithZonesRequest\x12\x1f\n" +
	"\vpackage_ids\x18\x01 \x03(\tR\n" +
	"packageIds\"G\n" +
	"\x1cGetPackagesWithZonesResponse\x12'\n" +
	"\bpackages\x18\x01 \x03(\v2\v.pb.PackageR\bpackages\"H\n" +
	"\aPackage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bzone_ids\x18\x03 \x03(\tR\azoneIds2k\n" +
	"\x0ePackageService\x12Y\n" +
	"\x14GetPackagesWithZones\x12\x1f.pb.GetPackagesWithZonesRequest\x1a .pb.GetPackagesWithZonesResponseB\tZ\a./protob\x06proto3"

var (
	file_package_proto_rawDescOnce sync.Once
	file_package_proto_rawDescData []byte
)

func file_package_proto_rawDescGZIP() []byte {
	file_package_proto_rawDescOnce.Do(func() {
		file_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_package_proto_rawDesc), len(file_package_proto_rawDesc)))
	})
	return file_package_proto_rawDescData
}

var file_package_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_package_proto_goTypes = []any{
	(*GetPackagesWithZonesRequest)(nil),  // 0: pb.GetPackagesWithZonesRequest
	(*GetPackagesWithZonesResponse)(nil), // 1: pb.GetPackagesWithZonesResponse
	(*Package)(nil),                      // 2: pb.Package
}
var file_package_proto_depIdxs = []int32{
	2, // 0: pb.GetPackagesWithZonesResponse.packages:type_name -> pb.Package
	0, // 1: pb.PackageService.GetPackagesWithZones:input_type -> pb.GetPackagesWithZonesRequest
	1, // 2: pb.PackageService.GetPackagesWithZones:output_type -> pb.GetPackagesWithZonesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_package_proto_init() }
func file_package_proto_init() {
	if File_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_package_proto_rawDesc), len(file_package_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_package_proto_goTypes,
		DependencyIndexes: file_package_proto_depIdxs,
		MessageInfos:      file_package_proto_msgTypes,
	}.Build()
	File_package_proto = out.File
	file_package_proto_goTypes = nil
	file_package_proto_depIdxs = nil
}
