[app]
name = "ProfileMonitor"
port = ":8081"
log_level = "debug"

[kafka]
brokers = ["localhost:9092"]
topic = "profile-indexer.active-profiles"

[postgres]
connection_string = "postgres://postgres:1@localhost:5432/profile_storage"

[worker]
delay = "5s"
