// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: profilesLimits.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfilesLimitsService_GetProfilesLimits_FullMethodName = "/profilesLimits.ProfilesLimitsService/GetProfilesLimits"
)

// ProfilesLimitsServiceClient is the client API for ProfilesLimitsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfilesLimitsServiceClient interface {
	GetProfilesLimits(ctx context.Context, in *GetProfilesLimitsRequest, opts ...grpc.CallOption) (*GetProfilesLimitsResponse, error)
}

type profilesLimitsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfilesLimitsServiceClient(cc grpc.ClientConnInterface) ProfilesLimitsServiceClient {
	return &profilesLimitsServiceClient{cc}
}

func (c *profilesLimitsServiceClient) GetProfilesLimits(ctx context.Context, in *GetProfilesLimitsRequest, opts ...grpc.CallOption) (*GetProfilesLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfilesLimitsResponse)
	err := c.cc.Invoke(ctx, ProfilesLimitsService_GetProfilesLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilesLimitsServiceServer is the server API for ProfilesLimitsService service.
// All implementations must embed UnimplementedProfilesLimitsServiceServer
// for forward compatibility.
type ProfilesLimitsServiceServer interface {
	GetProfilesLimits(context.Context, *GetProfilesLimitsRequest) (*GetProfilesLimitsResponse, error)
	mustEmbedUnimplementedProfilesLimitsServiceServer()
}

// UnimplementedProfilesLimitsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfilesLimitsServiceServer struct{}

func (UnimplementedProfilesLimitsServiceServer) GetProfilesLimits(context.Context, *GetProfilesLimitsRequest) (*GetProfilesLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfilesLimits not implemented")
}
func (UnimplementedProfilesLimitsServiceServer) mustEmbedUnimplementedProfilesLimitsServiceServer() {}
func (UnimplementedProfilesLimitsServiceServer) testEmbeddedByValue()                               {}

// UnsafeProfilesLimitsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfilesLimitsServiceServer will
// result in compilation errors.
type UnsafeProfilesLimitsServiceServer interface {
	mustEmbedUnimplementedProfilesLimitsServiceServer()
}

func RegisterProfilesLimitsServiceServer(s grpc.ServiceRegistrar, srv ProfilesLimitsServiceServer) {
	// If the following call pancis, it indicates UnimplementedProfilesLimitsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfilesLimitsService_ServiceDesc, srv)
}

func _ProfilesLimitsService_GetProfilesLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfilesLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesLimitsServiceServer).GetProfilesLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfilesLimitsService_GetProfilesLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesLimitsServiceServer).GetProfilesLimits(ctx, req.(*GetProfilesLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfilesLimitsService_ServiceDesc is the grpc.ServiceDesc for ProfilesLimitsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfilesLimitsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profilesLimits.ProfilesLimitsService",
	HandlerType: (*ProfilesLimitsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfilesLimits",
			Handler:    _ProfilesLimitsService_GetProfilesLimits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profilesLimits.proto",
}
