name = "StateService"
log_level = "debug"

[profiles_limits]
address = "localhost:8081"

[redis]
connection_string = "redis://:1@localhost:6379/0"

[manager]
refresh_delay = "1s"

[server]
port = "8086"


