// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: profilesByZone.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileByZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByZoneRequest) Reset() {
	*x = GetProfileByZoneRequest{}
	mi := &file_profilesByZone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByZoneRequest) ProtoMessage() {}

func (x *GetProfileByZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profilesByZone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByZoneRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByZoneRequest) Descriptor() ([]byte, []int) {
	return file_profilesByZone_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileByZoneRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type GetProfilesByZoneResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProfilesByPackage map[string]*ProfileIds `protobuf:"bytes,1,rep,name=profilesByPackage,proto3" json:"profilesByPackage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ProfilesByUUID    map[string]*Profile    `protobuf:"bytes,2,rep,name=profilesByUUID,proto3" json:"profilesByUUID,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProfilesByZoneResponse) Reset() {
	*x = GetProfilesByZoneResponse{}
	mi := &file_profilesByZone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesByZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesByZoneResponse) ProtoMessage() {}

func (x *GetProfilesByZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profilesByZone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesByZoneResponse.ProtoReflect.Descriptor instead.
func (*GetProfilesByZoneResponse) Descriptor() ([]byte, []int) {
	return file_profilesByZone_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfilesByZoneResponse) GetProfilesByPackage() map[string]*ProfileIds {
	if x != nil {
		return x.ProfilesByPackage
	}
	return nil
}

func (x *GetProfilesByZoneResponse) GetProfilesByUUID() map[string]*Profile {
	if x != nil {
		return x.ProfilesByUUID
	}
	return nil
}

type ProfileIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=Ids,proto3" json:"Ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileIds) Reset() {
	*x = ProfileIds{}
	mi := &file_profilesByZone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileIds) ProtoMessage() {}

func (x *ProfileIds) ProtoReflect() protoreflect.Message {
	mi := &file_profilesByZone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileIds.ProtoReflect.Descriptor instead.
func (*ProfileIds) Descriptor() ([]byte, []int) {
	return file_profilesByZone_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileIds) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Profile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BidPrice          float32                `protobuf:"fixed32,3,opt,name=bidPrice,proto3" json:"bidPrice,omitempty"`
	Creatives         map[string]*Creative   `protobuf:"bytes,4,rep,name=creatives,proto3" json:"creatives,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ProfilesTargeting map[string]string      `protobuf:"bytes,5,rep,name=profilesTargeting,proto3" json:"profilesTargeting,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profilesByZone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profilesByZone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profilesByZone_proto_rawDescGZIP(), []int{3}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetBidPrice() float32 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *Profile) GetCreatives() map[string]*Creative {
	if x != nil {
		return x.Creatives
	}
	return nil
}

func (x *Profile) GetProfilesTargeting() map[string]string {
	if x != nil {
		return x.ProfilesTargeting
	}
	return nil
}

type Creative struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaURL      string                 `protobuf:"bytes,2,opt,name=mediaURL,proto3" json:"mediaURL,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	CreativeType  string                 `protobuf:"bytes,5,opt,name=creativeType,proto3" json:"creativeType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Creative) Reset() {
	*x = Creative{}
	mi := &file_profilesByZone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Creative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Creative) ProtoMessage() {}

func (x *Creative) ProtoReflect() protoreflect.Message {
	mi := &file_profilesByZone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Creative.ProtoReflect.Descriptor instead.
func (*Creative) Descriptor() ([]byte, []int) {
	return file_profilesByZone_proto_rawDescGZIP(), []int{4}
}

func (x *Creative) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Creative) GetMediaURL() string {
	if x != nil {
		return x.MediaURL
	}
	return ""
}

func (x *Creative) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Creative) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Creative) GetCreativeType() string {
	if x != nil {
		return x.CreativeType
	}
	return ""
}

var File_profilesByZone_proto protoreflect.FileDescriptor

const file_profilesByZone_proto_rawDesc = "" +
	"\n" +
	"\x14profilesByZone.proto\x12\x02pb\"2\n" +
	"\x17GetProfileByZoneRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\"\x80\x03\n" +
	"\x19GetProfilesByZoneResponse\x12b\n" +
	"\x11profilesByPackage\x18\x01 \x03(\v24.pb.GetProfilesByZoneResponse.ProfilesByPackageEntryR\x11profilesByPackage\x12Y\n" +
	"\x0eprofilesByUUID\x18\x02 \x03(\v21.pb.GetProfilesByZoneResponse.ProfilesByUUIDEntryR\x0eprofilesByUUID\x1aT\n" +
	"\x16ProfilesByPackageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.pb.ProfileIdsR\x05value:\x028\x01\x1aN\n" +
	"\x13ProfilesByUUIDEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.pb.ProfileR\x05value:\x028\x01\"\x1e\n" +
	"\n" +
	"ProfileIds\x12\x10\n" +
	"\x03Ids\x18\x01 \x03(\tR\x03Ids\"\xe7\x02\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bbidPrice\x18\x03 \x01(\x02R\bbidPrice\x128\n" +
	"\tcreatives\x18\x04 \x03(\v2\x1a.pb.Profile.CreativesEntryR\tcreatives\x12P\n" +
	"\x11profilesTargeting\x18\x05 \x03(\v2\".pb.Profile.ProfilesTargetingEntryR\x11profilesTargeting\x1aJ\n" +
	"\x0eCreativesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.pb.CreativeR\x05value:\x028\x01\x1aD\n" +
	"\x16ProfilesTargetingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\bCreative\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bmediaURL\x18\x02 \x01(\tR\bmediaURL\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\"\n" +
	"\fcreativeType\x18\x05 \x01(\tR\fcreativeType2h\n" +
	"\x15ProfilesByZoneService\x12O\n" +
	"\x11GetProfilesByZone\x12\x1b.pb.GetProfileByZoneRequest\x1a\x1d.pb.GetProfilesByZoneResponseB\tZ\a./protob\x06proto3"

var (
	file_profilesByZone_proto_rawDescOnce sync.Once
	file_profilesByZone_proto_rawDescData []byte
)

func file_profilesByZone_proto_rawDescGZIP() []byte {
	file_profilesByZone_proto_rawDescOnce.Do(func() {
		file_profilesByZone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profilesByZone_proto_rawDesc), len(file_profilesByZone_proto_rawDesc)))
	})
	return file_profilesByZone_proto_rawDescData
}

var file_profilesByZone_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_profilesByZone_proto_goTypes = []any{
	(*GetProfileByZoneRequest)(nil),   // 0: pb.GetProfileByZoneRequest
	(*GetProfilesByZoneResponse)(nil), // 1: pb.GetProfilesByZoneResponse
	(*ProfileIds)(nil),                // 2: pb.ProfileIds
	(*Profile)(nil),                   // 3: pb.Profile
	(*Creative)(nil),                  // 4: pb.Creative
	nil,                               // 5: pb.GetProfilesByZoneResponse.ProfilesByPackageEntry
	nil,                               // 6: pb.GetProfilesByZoneResponse.ProfilesByUUIDEntry
	nil,                               // 7: pb.Profile.CreativesEntry
	nil,                               // 8: pb.Profile.ProfilesTargetingEntry
}
var file_profilesByZone_proto_depIdxs = []int32{
	5, // 0: pb.GetProfilesByZoneResponse.profilesByPackage:type_name -> pb.GetProfilesByZoneResponse.ProfilesByPackageEntry
	6, // 1: pb.GetProfilesByZoneResponse.profilesByUUID:type_name -> pb.GetProfilesByZoneResponse.ProfilesByUUIDEntry
	7, // 2: pb.Profile.creatives:type_name -> pb.Profile.CreativesEntry
	8, // 3: pb.Profile.profilesTargeting:type_name -> pb.Profile.ProfilesTargetingEntry
	2, // 4: pb.GetProfilesByZoneResponse.ProfilesByPackageEntry.value:type_name -> pb.ProfileIds
	3, // 5: pb.GetProfilesByZoneResponse.ProfilesByUUIDEntry.value:type_name -> pb.Profile
	4, // 6: pb.Profile.CreativesEntry.value:type_name -> pb.Creative
	0, // 7: pb.ProfilesByZoneService.GetProfilesByZone:input_type -> pb.GetProfileByZoneRequest
	1, // 8: pb.ProfilesByZoneService.GetProfilesByZone:output_type -> pb.GetProfilesByZoneResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_profilesByZone_proto_init() }
func file_profilesByZone_proto_init() {
	if File_profilesByZone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profilesByZone_proto_rawDesc), len(file_profilesByZone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profilesByZone_proto_goTypes,
		DependencyIndexes: file_profilesByZone_proto_depIdxs,
		MessageInfos:      file_profilesByZone_proto_msgTypes,
	}.Build()
	File_profilesByZone_proto = out.File
	file_profilesByZone_proto_goTypes = nil
	file_profilesByZone_proto_depIdxs = nil
}
