// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: getProfileState.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileStateRequest) Reset() {
	*x = GetProfileStateRequest{}
	mi := &file_getProfileState_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileStateRequest) ProtoMessage() {}

func (x *GetProfileStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getProfileState_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileStateRequest.ProtoReflect.Descriptor instead.
func (*GetProfileStateRequest) Descriptor() ([]byte, []int) {
	return file_getProfileState_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileStateRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type GetProfileStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         int32                  `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileStateResponse) Reset() {
	*x = GetProfileStateResponse{}
	mi := &file_getProfileState_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileStateResponse) ProtoMessage() {}

func (x *GetProfileStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_getProfileState_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileStateResponse.ProtoReflect.Descriptor instead.
func (*GetProfileStateResponse) Descriptor() ([]byte, []int) {
	return file_getProfileState_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileStateResponse) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_getProfileState_proto protoreflect.FileDescriptor

const file_getProfileState_proto_rawDesc = "" +
	"\n" +
	"\x15getProfileState.proto\x12\x02pb\"7\n" +
	"\x16GetProfileStateRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"/\n" +
	"\x17GetProfileStateResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\x05R\x05state2a\n" +
	"\x13ProfileStateService\x12J\n" +
	"\x0fGetProfileState\x12\x1a.pb.GetProfileStateRequest\x1a\x1b.pb.GetProfileStateResponseB\tZ\a./protob\x06proto3"

var (
	file_getProfileState_proto_rawDescOnce sync.Once
	file_getProfileState_proto_rawDescData []byte
)

func file_getProfileState_proto_rawDescGZIP() []byte {
	file_getProfileState_proto_rawDescOnce.Do(func() {
		file_getProfileState_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_getProfileState_proto_rawDesc), len(file_getProfileState_proto_rawDesc)))
	})
	return file_getProfileState_proto_rawDescData
}

var file_getProfileState_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getProfileState_proto_goTypes = []any{
	(*GetProfileStateRequest)(nil),  // 0: pb.GetProfileStateRequest
	(*GetProfileStateResponse)(nil), // 1: pb.GetProfileStateResponse
}
var file_getProfileState_proto_depIdxs = []int32{
	0, // 0: pb.ProfileStateService.GetProfileState:input_type -> pb.GetProfileStateRequest
	1, // 1: pb.ProfileStateService.GetProfileState:output_type -> pb.GetProfileStateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getProfileState_proto_init() }
func file_getProfileState_proto_init() {
	if File_getProfileState_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_getProfileState_proto_rawDesc), len(file_getProfileState_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getProfileState_proto_goTypes,
		DependencyIndexes: file_getProfileState_proto_depIdxs,
		MessageInfos:      file_getProfileState_proto_msgTypes,
	}.Build()
	File_getProfileState_proto = out.File
	file_getProfileState_proto_goTypes = nil
	file_getProfileState_proto_depIdxs = nil
}
