// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: profiles.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesRequest) Reset() {
	*x = GetProfilesRequest{}
	mi := &file_profiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesRequest) ProtoMessage() {}

func (x *GetProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetProfilesRequest) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{0}
}

type Creative struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,2,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	CreativeType  string                 `protobuf:"bytes,5,opt,name=creative_type,json=creativeType,proto3" json:"creative_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Creative) Reset() {
	*x = Creative{}
	mi := &file_profiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Creative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Creative) ProtoMessage() {}

func (x *Creative) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Creative.ProtoReflect.Descriptor instead.
func (*Creative) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{1}
}

func (x *Creative) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Creative) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Creative) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Creative) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Creative) GetCreativeType() string {
	if x != nil {
		return x.CreativeType
	}
	return ""
}

type Profile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BidPrice         float32                `protobuf:"fixed32,3,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	Creatives        map[string]*Creative   `protobuf:"bytes,4,rep,name=creatives,proto3" json:"creatives,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[uuid]string -> Creative
	PackageIds       []string               `protobuf:"bytes,5,rep,name=package_ids,json=packageIds,proto3" json:"package_ids,omitempty"`                                                       // UUIDs як рядки
	ProfileTargeting map[string]string      `protobuf:"bytes,6,rep,name=profile_targeting,json=profileTargeting,proto3" json:"profile_targeting,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profiles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{2}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetBidPrice() float32 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *Profile) GetCreatives() map[string]*Creative {
	if x != nil {
		return x.Creatives
	}
	return nil
}

func (x *Profile) GetPackageIds() []string {
	if x != nil {
		return x.PackageIds
	}
	return nil
}

func (x *Profile) GetProfileTargeting() map[string]string {
	if x != nil {
		return x.ProfileTargeting
	}
	return nil
}

type GetProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesResponse) Reset() {
	*x = GetProfilesResponse{}
	mi := &file_profiles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesResponse) ProtoMessage() {}

func (x *GetProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesResponse.ProtoReflect.Descriptor instead.
func (*GetProfilesResponse) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type GetProfilesLimitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesLimitsRequest) Reset() {
	*x = GetProfilesLimitsRequest{}
	mi := &file_profiles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesLimitsRequest) ProtoMessage() {}

func (x *GetProfilesLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesLimitsRequest.ProtoReflect.Descriptor instead.
func (*GetProfilesLimitsRequest) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{4}
}

type ProfilesWithLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ViewsLimits   int32                  `protobuf:"varint,2,opt,name=views_limits,json=viewsLimits,proto3" json:"views_limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesWithLimits) Reset() {
	*x = ProfilesWithLimits{}
	mi := &file_profiles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesWithLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesWithLimits) ProtoMessage() {}

func (x *ProfilesWithLimits) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesWithLimits.ProtoReflect.Descriptor instead.
func (*ProfilesWithLimits) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{5}
}

func (x *ProfilesWithLimits) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfilesWithLimits) GetViewsLimits() int32 {
	if x != nil {
		return x.ViewsLimits
	}
	return 0
}

type GetProfilesLimitsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProfilesWithLimits []*ProfilesWithLimits  `protobuf:"bytes,1,rep,name=profilesWithLimits,proto3" json:"profilesWithLimits,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProfilesLimitsResponse) Reset() {
	*x = GetProfilesLimitsResponse{}
	mi := &file_profiles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesLimitsResponse) ProtoMessage() {}

func (x *GetProfilesLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profiles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesLimitsResponse.ProtoReflect.Descriptor instead.
func (*GetProfilesLimitsResponse) Descriptor() ([]byte, []int) {
	return file_profiles_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfilesLimitsResponse) GetProfilesWithLimits() []*ProfilesWithLimits {
	if x != nil {
		return x.ProfilesWithLimits
	}
	return nil
}

var File_profiles_proto protoreflect.FileDescriptor

const file_profiles_proto_rawDesc = "" +
	"\n" +
	"\x0eprofiles.proto\x12\bprofiles\"\x14\n" +
	"\x12GetProfilesRequest\"\x8a\x01\n" +
	"\bCreative\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmedia_url\x18\x02 \x01(\tR\bmediaUrl\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12#\n" +
	"\rcreative_type\x18\x05 \x01(\tR\fcreativeType\"\x98\x03\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tbid_price\x18\x03 \x01(\x02R\bbidPrice\x12>\n" +
	"\tcreatives\x18\x04 \x03(\v2 .profiles.Profile.CreativesEntryR\tcreatives\x12\x1f\n" +
	"\vpackage_ids\x18\x05 \x03(\tR\n" +
	"packageIds\x12T\n" +
	"\x11profile_targeting\x18\x06 \x03(\v2'.profiles.Profile.ProfileTargetingEntryR\x10profileTargeting\x1aP\n" +
	"\x0eCreativesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.profiles.CreativeR\x05value:\x028\x01\x1aC\n" +
	"\x15ProfileTargetingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x13GetProfilesResponse\x12-\n" +
	"\bprofiles\x18\x01 \x03(\v2\x11.profiles.ProfileR\bprofiles\"\x1a\n" +
	"\x18GetProfilesLimitsRequest\"G\n" +
	"\x12ProfilesWithLimits\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fviews_limits\x18\x02 \x01(\x05R\vviewsLimits\"i\n" +
	"\x19GetProfilesLimitsResponse\x12L\n" +
	"\x12profilesWithLimits\x18\x01 \x03(\v2\x1c.profiles.ProfilesWithLimitsR\x12profilesWithLimits2\xc1\x01\n" +
	"\x0fProfilesService\x12P\n" +
	"\x11GetActiveProfiles\x12\x1c.profiles.GetProfilesRequest\x1a\x1d.profiles.GetProfilesResponse\x12\\\n" +
	"\x11GetProfilesLimits\x12\".profiles.GetProfilesLimitsRequest\x1a#.profiles.GetProfilesLimitsResponseB\bZ\x06/protob\x06proto3"

var (
	file_profiles_proto_rawDescOnce sync.Once
	file_profiles_proto_rawDescData []byte
)

func file_profiles_proto_rawDescGZIP() []byte {
	file_profiles_proto_rawDescOnce.Do(func() {
		file_profiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profiles_proto_rawDesc), len(file_profiles_proto_rawDesc)))
	})
	return file_profiles_proto_rawDescData
}

var file_profiles_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_profiles_proto_goTypes = []any{
	(*GetProfilesRequest)(nil),        // 0: profiles.GetProfilesRequest
	(*Creative)(nil),                  // 1: profiles.Creative
	(*Profile)(nil),                   // 2: profiles.Profile
	(*GetProfilesResponse)(nil),       // 3: profiles.GetProfilesResponse
	(*GetProfilesLimitsRequest)(nil),  // 4: profiles.GetProfilesLimitsRequest
	(*ProfilesWithLimits)(nil),        // 5: profiles.ProfilesWithLimits
	(*GetProfilesLimitsResponse)(nil), // 6: profiles.GetProfilesLimitsResponse
	nil,                               // 7: profiles.Profile.CreativesEntry
	nil,                               // 8: profiles.Profile.ProfileTargetingEntry
}
var file_profiles_proto_depIdxs = []int32{
	7, // 0: profiles.Profile.creatives:type_name -> profiles.Profile.CreativesEntry
	8, // 1: profiles.Profile.profile_targeting:type_name -> profiles.Profile.ProfileTargetingEntry
	2, // 2: profiles.GetProfilesResponse.profiles:type_name -> profiles.Profile
	5, // 3: profiles.GetProfilesLimitsResponse.profilesWithLimits:type_name -> profiles.ProfilesWithLimits
	1, // 4: profiles.Profile.CreativesEntry.value:type_name -> profiles.Creative
	0, // 5: profiles.ProfilesService.GetActiveProfiles:input_type -> profiles.GetProfilesRequest
	4, // 6: profiles.ProfilesService.GetProfilesLimits:input_type -> profiles.GetProfilesLimitsRequest
	3, // 7: profiles.ProfilesService.GetActiveProfiles:output_type -> profiles.GetProfilesResponse
	6, // 8: profiles.ProfilesService.GetProfilesLimits:output_type -> profiles.GetProfilesLimitsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_profiles_proto_init() }
func file_profiles_proto_init() {
	if File_profiles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profiles_proto_rawDesc), len(file_profiles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profiles_proto_goTypes,
		DependencyIndexes: file_profiles_proto_depIdxs,
		MessageInfos:      file_profiles_proto_msgTypes,
	}.Build()
	File_profiles_proto = out.File
	file_profiles_proto_goTypes = nil
	file_profiles_proto_depIdxs = nil
}
