// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: incrementViews.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdateCounterService_UpdateCounterOnProfile_FullMethodName = "/pb.UpdateCounterService/UpdateCounterOnProfile"
)

// UpdateCounterServiceClient is the client API for UpdateCounterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateCounterServiceClient interface {
	UpdateCounterOnProfile(ctx context.Context, in *UpdateCounterRequest, opts ...grpc.CallOption) (*UpdateCounterResponse, error)
}

type updateCounterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateCounterServiceClient(cc grpc.ClientConnInterface) UpdateCounterServiceClient {
	return &updateCounterServiceClient{cc}
}

func (c *updateCounterServiceClient) UpdateCounterOnProfile(ctx context.Context, in *UpdateCounterRequest, opts ...grpc.CallOption) (*UpdateCounterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCounterResponse)
	err := c.cc.Invoke(ctx, UpdateCounterService_UpdateCounterOnProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateCounterServiceServer is the server API for UpdateCounterService service.
// All implementations must embed UnimplementedUpdateCounterServiceServer
// for forward compatibility.
type UpdateCounterServiceServer interface {
	UpdateCounterOnProfile(context.Context, *UpdateCounterRequest) (*UpdateCounterResponse, error)
	mustEmbedUnimplementedUpdateCounterServiceServer()
}

// UnimplementedUpdateCounterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateCounterServiceServer struct{}

func (UnimplementedUpdateCounterServiceServer) UpdateCounterOnProfile(context.Context, *UpdateCounterRequest) (*UpdateCounterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCounterOnProfile not implemented")
}
func (UnimplementedUpdateCounterServiceServer) mustEmbedUnimplementedUpdateCounterServiceServer() {}
func (UnimplementedUpdateCounterServiceServer) testEmbeddedByValue()                              {}

// UnsafeUpdateCounterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateCounterServiceServer will
// result in compilation errors.
type UnsafeUpdateCounterServiceServer interface {
	mustEmbedUnimplementedUpdateCounterServiceServer()
}

func RegisterUpdateCounterServiceServer(s grpc.ServiceRegistrar, srv UpdateCounterServiceServer) {
	// If the following call pancis, it indicates UnimplementedUpdateCounterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateCounterService_ServiceDesc, srv)
}

func _UpdateCounterService_UpdateCounterOnProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateCounterServiceServer).UpdateCounterOnProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateCounterService_UpdateCounterOnProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateCounterServiceServer).UpdateCounterOnProfile(ctx, req.(*UpdateCounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateCounterService_ServiceDesc is the grpc.ServiceDesc for UpdateCounterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateCounterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UpdateCounterService",
	HandlerType: (*UpdateCounterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCounterOnProfile",
			Handler:    _UpdateCounterService_UpdateCounterOnProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "incrementViews.proto",
}
