// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: incrementViews.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateCounterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCounterRequest) Reset() {
	*x = UpdateCounterRequest{}
	mi := &file_incrementViews_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCounterRequest) ProtoMessage() {}

func (x *UpdateCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incrementViews_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCounterRequest.ProtoReflect.Descriptor instead.
func (*UpdateCounterRequest) Descriptor() ([]byte, []int) {
	return file_incrementViews_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateCounterRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type UpdateCounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCounterResponse) Reset() {
	*x = UpdateCounterResponse{}
	mi := &file_incrementViews_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCounterResponse) ProtoMessage() {}

func (x *UpdateCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incrementViews_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCounterResponse.ProtoReflect.Descriptor instead.
func (*UpdateCounterResponse) Descriptor() ([]byte, []int) {
	return file_incrementViews_proto_rawDescGZIP(), []int{1}
}

var File_incrementViews_proto protoreflect.FileDescriptor

const file_incrementViews_proto_rawDesc = "" +
	"\n" +
	"\x14incrementViews.proto\x12\x02pb\"5\n" +
	"\x14UpdateCounterRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"\x17\n" +
	"\x15UpdateCounterResponse2e\n" +
	"\x14UpdateCounterService\x12M\n" +
	"\x16UpdateCounterOnProfile\x12\x18.pb.UpdateCounterRequest\x1a\x19.pb.UpdateCounterResponseB\tZ\a./protob\x06proto3"

var (
	file_incrementViews_proto_rawDescOnce sync.Once
	file_incrementViews_proto_rawDescData []byte
)

func file_incrementViews_proto_rawDescGZIP() []byte {
	file_incrementViews_proto_rawDescOnce.Do(func() {
		file_incrementViews_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incrementViews_proto_rawDesc), len(file_incrementViews_proto_rawDesc)))
	})
	return file_incrementViews_proto_rawDescData
}

var file_incrementViews_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_incrementViews_proto_goTypes = []any{
	(*UpdateCounterRequest)(nil),  // 0: pb.UpdateCounterRequest
	(*UpdateCounterResponse)(nil), // 1: pb.UpdateCounterResponse
}
var file_incrementViews_proto_depIdxs = []int32{
	0, // 0: pb.UpdateCounterService.UpdateCounterOnProfile:input_type -> pb.UpdateCounterRequest
	1, // 1: pb.UpdateCounterService.UpdateCounterOnProfile:output_type -> pb.UpdateCounterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_incrementViews_proto_init() }
func file_incrementViews_proto_init() {
	if File_incrementViews_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incrementViews_proto_rawDesc), len(file_incrementViews_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_incrementViews_proto_goTypes,
		DependencyIndexes: file_incrementViews_proto_depIdxs,
		MessageInfos:      file_incrementViews_proto_msgTypes,
	}.Build()
	File_incrementViews_proto = out.File
	file_incrementViews_proto_goTypes = nil
	file_incrementViews_proto_depIdxs = nil
}
